services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - devdojo_maratona_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  devdojo_maratona_data:
